Entry/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import logout


app_name='Entry'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(),name='index'),

    url(r'^(?P<user_id>[0-9]+)/followed/$', views.FollowIndexView.as_view(),name='followed'),

    url(r'^(?P<user_id>[0-9]+)/followedby/$', views.FollowedByIndexView.as_view(),name='followedby'),

    url(r'^reviewer/register/$', views.ReviewerFormView.as_view(),name='reviewer-register'),

    url(r'^search-results/$', views.search,name='search-results'),

    url(r'^register/$', views.UserFormView.as_view(),name='register'),

    url(r'^login/$', views.LoginFormView.as_view(),name='login'),

    url(r'^logout/$', logout, {'next_page': '/entry/login'},name='logout'),


    url(r'^profile/add/$',views.ProfileCreate.as_view(),name='profile-create'),

    
    url(r'^profile/(?P<pk>[0-9]+)/$',views.ProfileUpdate.as_view(),name='profile-update'),


    url(r'^userdetail/(?P<pk>[0-9]+)/$',views.UserDetailView.as_view(),name='userdetail'),

    url(r'^userdetail/(?P<pk>[0-9]+)/follow/$',views.follow,name='follow'),

    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),

    url(r'^(?P<entry_id>[0-9]+)/rate/$',views.rate,name='rate'),

    

	url(r'^(?P<entry_id>[0-9]+)/like/$',views.like,name='like'),

    url(r'^(?P<entry_id>[0-9]+)/bookmark/$',views.bookmark,name='bookmark'),



	url(r'^entry/add/$',views.EntryCreate.as_view(),name='entry-add'),

    url(r'^entry/myworks/$',views.MyWorks.as_view(),name='myworks'),

    url(r'^entry/liked/$',views.MyLikes.as_view(),name='liked-entries'),

    url(r'^entry/bookmarked/$',views.MyBookmarks.as_view(),name='bookmarked-entries'),



	url(r'^entry/(?P<pk>[0-9]+)/$',views.EntryUpdate.as_view(),name='entry-update'),

	url(r'^entry/(?P<pk>[0-9]+)/delete/$',views.EntryDelete.as_view(),name='entry-delete'),

]

Scribble/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth.views import logout
urlpatterns = [


    url(r'^admin/logout/$', logout,
    {'next_page': '/entry/login'}),
    url(r'^admin/', admin.site.urls),
    url(r'^entry/',include('Entry.urls')),
]

Entry/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone


from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator

# Create your models here.



class Profile(models.Model):
	#user_id=models.IntegerField()
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	birth_date=models.DateField(null=True,blank=True)

	def get_absolute_url(self):
		return reverse('Entry:index')

	def __str__(self):
		return self.user.username

class Genre(models.Model):
	#genre_id=models.IntegerField()
	genre_name=models.CharField(max_length=20)

	def __str__(self):
		return self.genre_name

class Writing_Style(models.Model):
	writing_style=models.CharField(max_length=20)

	def __str__(self):
		return self.writing_style



class Entry(models.Model):
	#entry_id=models.IntegerField()
	entry_name=models.CharField(max_length=40)
	entry_description=models.CharField(max_length=5000,default='Empty')
	entry_style=models.ForeignKey(Writing_Style,on_delete=models.CASCADE)
	entry_genres=models.ManyToManyField(Genre)
	entry_writer_id=models.ForeignKey(User,on_delete=models.CASCADE)
	entry_release_date=models.DateTimeField(default=timezone.now,blank=True)

	def get_absolute_url(self):
		return reverse('Entry:detail',kwargs={'pk':self.pk})
	def __str__(self):
		return self.entry_name



class Interest(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	genre=models.ForeignKey(Genre,on_delete=models.CASCADE)

class Follow(models.Model):
	following=models.ForeignKey(User,on_delete=models.CASCADE,related_name='following')
	follower=models.ForeignKey(User,on_delete=models.CASCADE,related_name='follower')

	

class Saves(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	entry=models.ForeignKey(Entry,on_delete=models.CASCADE)

class Likes(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	entry=models.ForeignKey(Entry,on_delete=models.CASCADE)

# class Reviewer(models.Model):
# 	reviewer=models.ForeignKey(User,on_delete=models.CASCADE)
# 	entries=models.ManyToManyField(Entry,through='Ratings')


# class Ratings(models.Model):
# 	reviewer=models.ForeignKey(Reviewer,on_delete=models.CASCADE)
# 	entry=models.ForeignKey(Entry,on_delete=models.CASCADE)
# 	stars=models.IntegerField( validators=[MaxValueValidator(5)])

Entry/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django import forms

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model=User
		fields=['username','email','password']


	



class LoginForm(forms.Form):

	username=forms.CharField()
	password=forms.CharField(widget=forms.PasswordInput)

Entry/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .models import Entry,Profile,Likes,Saves,Follow,Writing_Style,Genre
from .forms import UserForm,LoginForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User,Group
from django.http import HttpResponseRedirect








class IndexView(LoginRequiredMixin,generic.ListView):
	template_name='Entry/index.html'
	context_object_name='entry_list'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	redirect_unauthenticated_users =True
	#raise_exception = True


	def get_queryset(self):
		return Entry.objects.all()

class FollowIndexView(LoginRequiredMixin,generic.ListView):
	template_name='Entry/follow.html'
	context_object_name='follow_list'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	redirect_unauthenticated_users =True

	def get_queryset(self):

		return Follow.objects.filter(follower=self.kwargs['user_id'])

class FollowedByIndexView(LoginRequiredMixin,generic.ListView):
	template_name='Entry/followedby.html'
	context_object_name='followedby_list'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	redirect_unauthenticated_users =True

	def get_queryset(self):

		return Follow.objects.filter(following=self.kwargs['user_id'])

class MyWorks(LoginRequiredMixin,generic.ListView):
	template_name='Entry/myworks.html'
	context_object_name='entry_list'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	redirect_unauthenticated_users =True
	#raise_exception = True


	def get_queryset(self):
		return Entry.objects.all()

class MyLikes(LoginRequiredMixin,generic.ListView):
	template_name='Entry/mylikes.html'
	context_object_name='entry_list'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	redirect_unauthenticated_users =True
	#raise_exception = True


	def get_queryset(self):
		return Entry.objects.all()

class MyBookmarks(LoginRequiredMixin,generic.ListView):
	template_name='Entry/mybookmarks.html'
	context_object_name='entry_list'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	redirect_unauthenticated_users =True
	#raise_exception = True


	def get_queryset(self):
		return Entry.objects.all()



class DetailView(LoginRequiredMixin, generic.DetailView):
	model=Entry
	template_name='Entry/detail.html'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True


class UserDetailView(LoginRequiredMixin, generic.DetailView):
	model=User
	template_name='Entry/userdetail.html'
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True


class EntryCreate(LoginRequiredMixin, CreateView):
	model=Entry
	fields=['entry_name','entry_description','entry_style','entry_genres','entry_writer_id']
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True


class EntryUpdate(LoginRequiredMixin, UpdateView):
	model=Entry
	fields=['entry_name','entry_description','entry_style','entry_writer_id','entry_release_date']
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True

class ProfileCreate(LoginRequiredMixin, CreateView):
	model=Profile
	fields=['user','birth_date']
	login_url="/entry/login"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True

class ProfileUpdate(LoginRequiredMixin, UpdateView):
	model=Profile
	print 'hello'
	fields=['user','birth_date']
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True

class ProfileDelete(LoginRequiredMixin,DeleteView):
	model=Profile
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True

	def get_success_url(self):

		return reverse_lazy('Entry:index')


class EntryDelete(LoginRequiredMixin,DeleteView):
	model=Entry
	login_url = "/entry/login/"
	redirect_field_name = "rollback"
	#raise_exception = True
	redirect_unauthenticated_users= True

	def get_success_url(self):

		return reverse_lazy('Entry:index')
	





class LoginFormView(View):
	form_class=LoginForm
	template_name='Lab/login.html'

	#display blank form	
	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})
	

	# process form data
	def post(self,request):
		form=self.form_class(request.POST)

			
		if form.is_valid():
		#cleaned data (formatted)
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			
			print username ,password

			#returns User object if credentials are correct

			user=authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request, user)
					  
					return redirect('/entry')
				else:
					return HttpResponse("You're account is disabled.")
			else:
				  # Return an 'invalid login' error message.
				print  "invalid login details username password"
				return render(request,self.template_name,{'form':form})

	

class UserFormView(View):
	template_name='Lab/registration.html'



	#display blank form	
	def get(self,request):
		form=UserForm(None)
		return render(request,self.template_name,{
			'form':form,
			})
	

	# process form data
	def post(self,request):
		form=UserForm(request.POST)

		if form.is_valid() :

			user=form.save(commit=False)

			#cleaned data (formatted)
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']


			user.set_password(password)
			
			user.save()
			user.groups.add(Group.objects.get(name='User'))
			
			return redirect('/entry/login')
		return render(request,self.template_name,{
			'form':form
			})


class ReviewerFormView(View):
	template_name='Entry/registration_index.html'



	#display blank form 
	def get(self,request):
		form=UserForm(None)
		return render(request,self.template_name,{
			'form':form,
			})
	

	# process form data
	def post(self,request):
		form=UserForm(request.POST)

		if form.is_valid() :

			user=form.save(commit=False)

			#cleaned data (formatted)
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']


			user.set_password(password)
			user.save()
			user.groups.add(Group.objects.get(name='Reviewer'))
			return redirect('/entry/login')
		return render(request,self.template_name,{
			'form':form
			})

def like(request,entry_id):
	entry=get_object_or_404(Entry,pk=entry_id)
	likes=Likes(user=request.user,entry=entry)
	likes.save()
	return redirect('/entry/')


def rate(request,entry_id):

	entry=get_object_or_404(Entry,pk=entry_id)


	

	return




def bookmark(request,entry_id):

	entry=get_object_or_404(Entry,pk=entry_id)
	bookmark=Saves(user=request.user,entry=entry)
	bookmark.save()
	return redirect('/entry/')


def follow(request,pk):
	following=get_object_or_404(User,pk=pk)
	follower=request.user
	follow=Follow(following=following,follower=follower)
	follow.save()
	return redirect('/entry/')


	return 

def search(request):
    ''' This could be your actual view or a new one '''
    # Your code
    if request.method == 'GET': # If the form is submitted

		search_query = request.GET.get('search_box', None)
		# Do whatever you need with the word the user looked for

		entry1=Entry.objects.filter(entry_name=search_query)

		
		style=Writing_Style.objects.filter(writing_style=search_query)
		
		entry2=Entry.objects.filter(entry_style=style)
		
		author=User.objects.filter(username=search_query)
		
		entry3=Entry.objects.filter(entry_writer_id=author)
		
		genre=Genre.objects.filter(genre_name=search_query)

		entry4=Entry.objects.filter(entry_genres =genre )

		

		entry_list=(entry1 | entry2 | entry3 | entry4).distinct()
		
		context={
		'entry_list':entry_list
		}

    return render(request,'Entry/searchresults.html',context)

Entry/templates/Entry/detail.html
{% extends 'Entry/base.html' %}

{% block title %}Entry Details {% endblock %}


{% block body %}

<!-- <div class="col-sm-4 col-lg-2">
<div class="thumbnail"> -->
	<div class = "TitleFont">
		<h2><b><u><center> {{entry.entry_name}}</center></u></b></h2>
	</div>
	<div class = "EntryFont">
		<h3><center>{{entry.entry_description}}</center></h3>
	</div>
	
	<br>
	<br>

<!-- </div>
</div> -->

<!-- <div class="col-sm-4 col-lg-2">
<div class="thumbnail"> -->
	<div class = "FooterFont">
	<h4><b>Style</b> : {{entry.entry_style}}</h4>

	<h4><b>Publish date</b> : {{entry.entry_release_date}}</h4>
	<h4><b>Genres</b> :{{entry.entry_genres.all}}</h4>
	</div>
	<br>

	<h5>
		<center>
			<span style="margin-right:40px">
		<a  href="{% url 'Entry:like' entry.id %}">
	        <button type="button" class="btn btn-success btn-xl">
	        	<span class="glyphicon glyphicon-heart"></span>&nbsp; Like
	        </button>
	    </a>
	   	</span>
		<a  href="{% url 'Entry:bookmark' entry.id %}">
	        <button type="button" class="btn btn-success btn-xl">
	        	<span class="glyphicon glyphicon-bookmark"></span>&nbsp; Bookmark
	        </button>
	    </a>
	    </center>
	</h5>
<!-- </div>
</div> -->

{% endblock %}

Entry/templates/Entry/follow.html
{% extends 'Entry/base.html' %}
{% load login_extras %}


<!-- {% block title %}Entry Index{% endblock %} -->

{% block body %}



      <div class="col-sm-12">
	                <div class="panel panel-default">
	                    <div class="panel-body">
	                        <table class="table">
	                            <thead>
	                                <tr>
	                                    <th>Following:</th>
	                                    
	                                    
	                                
	                                </tr>
	                            </thead>
	                            <tbody>
	                                {% for follow in follow_list %}

	                                    <tr>

	                                        <td>
	                                        	<a href="{% url 'Entry:userdetail' follow.following.id %}">
	                                        		<button type="button" class="btn btn-success btn-xs">
	                                                    <span class="glyphicon glyphicon-user"></span>&nbsp; 
	                                                    {{ follow.following.username }}
	                                                </button>
	                                            </a>

	                                        	
	                                        </td>

	                                        	                                 
	                                      
	                                    </tr>
	                                {% endfor %}
	                            </tbody>
	                        </table>
	                    </div>
	                </div>


            
       </div>
    

{% endblock %}

Entry/templates/Entry/followedby.html
{% extends 'Entry/base.html' %}
{% load login_extras %}


<!-- {% block title %}Entry Index{% endblock %} -->

{% block body %}



      <div class="col-sm-12">
	                <div class="panel panel-default">
	                    <div class="panel-body">
	                        <table class="table">
	                            <thead>
	                                <tr>
	                                    <th>Followed by:</th>
	                                    
	                                    
	                                
	                                </tr>
	                            </thead>
	                            <tbody>
	                                {% for followedby in followedby_list %}

	                                    <tr>

	                                        <td>
	                                        	<a href="{% url 'Entry:userdetail' followedby.follower.id %}">
	                                        		<button type="button" class="btn btn-success btn-xs">
	                                                    <span class="glyphicon glyphicon-user"></span>&nbsp; 
	                                                    {{ followedby.follower.username }}
	                                                </button>
	                                            </a>

	                                        	
	                                        </td>

	                                        	                                 
	                                      
	                                    </tr>
	                                {% endfor %}
	                            </tbody>
	                        </table>
	                    </div>
	                </div>


            
       </div>
    

{% endblock %}

Entry/templates/Entry/mybookmarks.html
{% extends 'Entry/base.html' %}
{% load login_extras %}
{% load staticfiles %}
<!-- {% block title %}Entry Index{% endblock %} -->

{% block body %}



      <div class="col-sm-12">
                <!-- <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Style</th>
                                    <th>Author</th>
                                    <th>Details</th>
                                    <th>Genres</th>
                                    <th>Release Date and Time<th>
                                    
                                    
                                
                                </tr>
                            </thead>
                            <tbody> -->
                                {% for entry in entry_list %}
                                    {% if request.user|has_bookmarked:entry %}

                                        <div class="col-sm-4 col-lg-2">
                                            <div class="thumbnail">
                                                <a href="{% url 'Entry:detail' entry.id %}">
                                                    <img src="{% static 'Entry/images/default.jpg' %}" class="img-responsive" alt="Test">
                                                </a>
                                                <div class="caption">
                                                    <h4><b>{{ entry.entry_name }}</b>
                                                        <span style="float:right;">
                                                            <!-- <a  href="{% url 'Entry:entry-update' entry.id %}">
                                                                <button type="button" class="btn btn-success btn-xs">
                                                                    <span class="glyphicon glyphicon-edit"></span>&nbsp; Update
                                                                </button>
                                                            </a>

                                                            <a  href="{% url 'Entry:entry-delete' entry.id %}">
                                                                <button type="button" class="btn btn-success btn-xs">
                                                                    <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete
                                                                </button>
                                                            </a>
 -->
                                                         </span>

                                                    </h4>
                                                    <!-- <h4>{{ entry.entry_writer_id.username }}</h4> -->

                                                    <!-- View Details -->
                                                    
                                                    <a href="{% url 'Entry:detail' entry.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                                    <!-- Delete Album -->
                                                    <!-- <form action="{% url 'Entry:bookmark' entry.id %}" method="post" style="display: inline;">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="entry_id" value="{{ entry.id }}" />
                                                        <button type="submit" class="btn btn-default btn-sm">
                                                            <span class="glyphicon glyphicon-bookmark"></span>
                                                        </button>
                                                    </form> -->
                                                    

                                                    <!-- Favorite Album -->
                                                    <a href="{% url 'Entry:like' entry.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                                        <span class="glyphicon glyphicon-thumbs-up "></span>
                                                    </a>
                                                    <b> Style : {{entry.entry_style}}</b>
                                                    <span style="float:right;"><a href="{% url 'Entry:userdetail' entry.entry_writer_id.id %}" class="btn btn-primary btn-sm" role="button">Author : {{ entry.entry_writer_id.username }}</a> </span>
                                                
                                                </div>
                                            </div>
                                        </div>

                                        <!-- <tr>
                                            <td>{{ entry.entry_name }}</td>
                                            <td>{{entry.entry_style}}</td>
                                            <td>{{ entry.entry_writer_id.username }}</td>
                                            
                                            <td>
                                                <a  href="{% url 'Entry:detail' entry.id %}">
                                                    <button type="button" class="btn btn-success btn-xs">
                                                        <span class="glyphicon glyphicon-zoom-in"></span>&nbsp; View
                                                    </button>
                                                </a>
                                            </td>
                                            <td>{{ entry.entry_genres.all }}</td>

                                            <td>{{entry.entry_release_date}}</td>
                                    
                                      
                                        </tr> -->
                                    {% endif %}
                                    
                                {% endfor %}
                            <!-- </tbody>
                        </table>
                    </div>
                </div> -->
            
       </div>
    

{% endblock %}

Entry/templates/Entry/mylikes.html
{% extends 'Entry/base.html' %}
{% load login_extras %}
{% load staticfiles %}

<!-- {% block title %}Entry Index{% endblock %} -->

{% block body %}



      <div class="col-sm-12">
                <!-- <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Style</th>
                                    <th>Author</th>
                                    <th>Details</th>
                                    <th>Genres</th>
                                    <th>Release Date and Time<th>
                                    
                                    
                                
                                </tr>
                            </thead>
                            <tbody> -->
                                {% for entry in entry_list %}
                                    {% if request.user|has_liked:entry %}


                                        <div class="col-sm-4 col-lg-2">
                                            <div class="thumbnail">
                                                <a href="{% url 'Entry:detail' entry.id %}">
                                                    <img src="{% static 'Entry/images/default.jpg' %}" class="img-responsive" alt="Test">
                                                </a>
                                                <div class="caption">
                                                    <h4><b>{{ entry.entry_name }}</b>
                                                        <span style="float:right;">
                                                            <!-- <a  href="{% url 'Entry:entry-update' entry.id %}">
                                                                <button type="button" class="btn btn-success btn-xs">
                                                                    <span class="glyphicon glyphicon-edit"></span>&nbsp; Update
                                                                </button>
                                                            </a>

                                                            <a  href="{% url 'Entry:entry-delete' entry.id %}">
                                                                <button type="button" class="btn btn-success btn-xs">
                                                                    <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete
                                                                </button>
                                                            </a>
 -->
                                                         </span>

                                                    </h4>
                                                    <!-- <h4>{{ entry.entry_writer_id.username }}</h4> -->

                                                    <!-- View Details -->
                                                    
                                                    <a href="{% url 'Entry:detail' entry.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                                    <!-- Delete Album -->
                                                    <form action="{% url 'Entry:bookmark' entry.id %}" method="post" style="display: inline;">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="entry_id" value="{{ entry.id }}" />
                                                        <button type="submit" class="btn btn-default btn-sm">
                                                            <span class="glyphicon glyphicon-bookmark"></span>
                                                        </button>
                                                    </form>
                                                    

                                                    <!-- Favorite Album -->
                                                    <!-- <a href="{% url 'Entry:like' entry.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                                        <span class="glyphicon glyphicon-thumbs-up "></span>
                                                    </a> -->
                                                    <b> Style : {{entry.entry_style}}</b>
                                                    <span style="float:right;"><a href="{% url 'Entry:userdetail' entry.entry_writer_id.id %}" class="btn btn-primary btn-sm" role="button">Author : {{ entry.entry_writer_id.username }}</a> </span>
                                                
                                                </div>
                                            </div>
                                        </div>
                                        <!-- <tr>
                                            <td>{{ entry.entry_name }}</td>
                                            <td>{{entry.entry_style}}</td>
                                            <td>{{ entry.entry_writer_id.username }}</td>
                                            
                                            <td>
                                                <a  href="{% url 'Entry:detail' entry.id %}">
                                                    <button type="button" class="btn btn-success btn-xs">
                                                        <span class="glyphicon glyphicon-zoom-in"></span>&nbsp; View
                                                    </button>
                                                </a>
                                            </td>
                                            <td>{{ entry.entry_genres.all }}</td>

                                            <td>{{entry.entry_release_date}}</td>
                                    
                                      
                                        </tr> -->
                                    {% endif %}
                                    
                                {% endfor %}
                            <!-- </tbody>
                        </table>
                    </div>
                </div> -->
            
       </div>
    

{% endblock %}

Entry/templates/Entry/userdetail.html
{% extends 'Entry/base.html' %}

{% block title %}User Details {% endblock %}

{% block body %}



	<h3> {{user.username}}:</h3>
	<h5>
		{% if request.user.username != user.username %}	
			<a  href="{% url 'Entry:follow' user.id %}">
		        <button type="button" class="btn btn-success btn-xs">
		        	<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Follow
		        </button>
		    </a>
	    {% endif %}
	</h5>

{% endblock %}